-- ═══════════════════════════════════════════════════════════
-- MIGRATION 020: Alerts table for agent layer
-- Stores alerts generated by Convergence, Causal, Allocation, Dispatch agents
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  entity_ref TEXT,
  summary TEXT NOT NULL,
  details JSONB DEFAULT '{}',
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
  acknowledged_by UUID,
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_status_severity
  ON public.alerts (status, severity, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_entity_ref
  ON public.alerts (entity_ref, created_at DESC);

-- RLS
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read alerts"
  ON public.alerts FOR SELECT USING (true);

CREATE POLICY "Service can manage alerts"
  ON public.alerts FOR ALL USING (true);
